# Generated by Django 4.2.5 on 2023-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/static/network/default.png', upload_to='profile_pics/'),
        ),
    ]
